### ISSUE TITLE
[REQUEST] Publish zigpy-cli on PyPi?

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy-cli#25]
@puddly Please consider publishing "zigpy-cli" on PyPI (similar to how zigpy is) so that it can more easily be used stand-alone:

https://pypi.org/project/zigpy

verses

https://pypi.org/project/zigpy-cli

Would be great if users want to use stand-alone zigpy-cli for backup and restore outside of Home Assistant's ZHA integration.

See these two use cases where the users are using Home Assistant SkyConnect USB adapter with Zigbee2MQTT instead of ZHA:

https://github.com/zigpy/zigpy-cli/discussions/24

https://github.com/Koenkk/zigbee2mqtt/discussions/16478

**Comment by puddly** [comment]
zigpy-cli is now available on PyPI: https://pypi.org/project/zigpy-cli/
