### ISSUE TITLE
Silicon Labs Zigbee EmberZNet 7.0.0.0 migrated to the new unified CLI system for Ember

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy-cli#8]
Silabs released Zigbee EmberZNet 7.0.0.0 which among other new things apper to migrate to a new unified CLI system for Ember:

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-7.0.0.0.pdf

https://docs.silabs.com/gecko-platform/4.0/service/cli/overview

http://docs.silabs.com/zigbee/7.0

They also for the first time release the Zigbee SDK publicly on GitHub

https://github.com/SiliconLabs/gecko_sdk/releases

https://github.com/SiliconLabs/gecko_sdk

https://github.com/SiliconLabs/gecko_sdk/tree/gsdk_4.0/protocol/zigbee

https://docs.silabs.com/gecko-platform/4.0/

### New in release 7.0.0.0

For an extensive list of new APIs in this release, refer to Zigbee Stack API documentation and Zigbee Application Framework API documentation on https://docs.silabs.com/ .

#### Command Line Interface (CLI)

Zigbee migrated to the new/unified CLI system. All `emberXXXArgument()` APIs are changed to `sl_cli_XXX_argument_XXX()`
APIs (e.g., `emberCommandArgumentCount() → sl_cli_get_argument_count()`). Refer to the `sl_cli.h` header file and its documentation
for available CLI command APIs.

In the newly integrated CLI, hexadecimal string and ASCII string arguments have dedicated types. These arguments can be retrieved
using the related APIs `sl_cli_get_command_string()` and `sl_cli_get_argument_hex()`. See `sl_cli.h` for more information.

### New in release 7.0.0.0
All components have documentation available. If you have an issue seeing the documentation when you select the component in Project Configurator, you can find it here: http://docs.silabs.com/zigbee/7.0

New software documentation available through Simplicity Studio’s Documentation page includes:

• AN1301: Transitioning from Zigbee EmberZNet SDK 6.x to SDK 7.x
• AN1322: Dynamic Multiprotocol Development with Bluetooth and and Zigbee EmberZNet SDK 7.0 and Higher
• AN1325: Zigbee Cluster Configurator User's Guide
• AN1333: Running Zigbee, OpenThread, and Bluetooth Concurrently on a Linux Host with a Multiprotocol RCP
• QSG180: Zigbee EmberZNet Quick-Start Guide for SDK 7.0 and Higher
• UG491: Zigbee Application Framework Developer’s Guide for SDK 7.0 and Higher

PS: Not sure if Gecko SDK 4.0 was accidentally released or official as of yet as their version history still says that Gecko SDK Suite 3.2 is latest:

https://docs.silabs.com/gecko-platform/latest/version-history

Link to 4.0 seem to work through:

https://docs.silabs.com/gecko-platform/4.0/

**Comment by Adminiuga** [comment]
What does this have to do with zigpy-cli other than CLI in the name?
